blank_issues_enabled: false
contact_links:
  - name: BDCC Discord
    url: https://discord.com/invite/7UGYBvQrc3
    about: Discord server where you can ask general questions and easily submitting mods or datapacks. You must be over 18 or not on Apple devices to join.